%% FUNCION QUE CALCULA LA DIST DEL PUNTO AL QUE QUIERO LLEGAR AL LIMITE DEL ESPACIO DE TRABAJO DEL STEPPER
function d= dist_etstep(pf)
 
 XSTEPMAX=450;
 XSTEPMIN=-460;
 
if pf(1)>0
d=XSTEPMAX-pf(1);
else d=-XSTEPMIN+pf(1);
end 
end